name: R-CMD-check

on:
  push:
    branches:
      - master  # Cambia esto si tu rama principal es diferente
  pull_request:
    branches:
      - master  # Cambia esto si tu rama principal es diferente

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          version: '4.4'  # Cambia esto a la versión de R que estás usando

      - name: Install Dependencies
        run: |
          install.packages('covr')  # Instala el paquete covr
          install.packages('remotes')  # Si necesitas remotes
          remotes::install_deps(dependencies = TRUE)  # Instala las dependencias

      - name: Run Tests
        run: |
          Rscript -e 'covr::codecov()'  # Ejecuta la función codecov

      - name: Upload Coverage to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}  # Usa el token de Codecov
        run: |
          Rscript -e 'covr::codecov()'  # Vuelve a ejecutar para cargar la cobertura
