name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages('remotes')
          remotes::install_deps(dependencies = TRUE)
          install.packages('covr')  # Instala covr para el reporte de cobertura

      - name: Run tests
        run: |
          R -e "devtools::check()"

      - name: Upload coverage to Codecov
        if: success()  # Solo sube el reporte si las pruebas pasan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          R -e "covr::codecov()"
