name: CI

on:
  push:
    branches:
      - master  # Cambiado de main a master
  pull_request:
    branches:
      - master  # Cambiado de main a master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: R -e 'install.packages("covr")'

      - name: Run tests with coverage
        run: R -e 'covr::codecov()'  # Esto sube los informes a Codecov
