name: R-CMD-check

on:
  push:
    branches:
      - master  # Cambia esto si tu rama principal es diferente
  pull_request:
    branches:
      - master  # Cambia esto si tu rama principal es diferente

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          version: '4.4.1'  # Cambia esto a la versión de R que estás usando

      - name: Install Dependencies
        run: |
          R -e "install.packages('covr')"
          R -e "install.packages('remotes')"  # Si usas remotes para instalar otras dependencias
          R -e "remotes::install_deps(dependencies = TRUE)"  # Instala las dependencias

      - name: Run Tests
        run: |
          R -e "library(testthat); test_dir('tests')"

      - name: Run Coverage and Upload
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}  # Usa el token de Codecov
        run: |
          R -e "library(covr); codecov()"

