name: R-CMD-check

on:
  push:
    branches:
      - master  # Cambia esto si usas una rama diferente
  pull_request:
    branches:
      - master  # Cambia esto si usas una rama diferente

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages('covr')
          install.packages('remotes')  # Si usas remotes para instalar otras dependencias
          remotes::install_deps(dependencies = TRUE)

      - name: Run tests
        run: R CMD build . && R CMD check *tar.gz --as-cran

      - name: Upload coverage to Codecov
        run: R -e 'covr::codecov()'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}  # Asegúrate de haber configurado tu token
